Repository SankethBK/diaryvault, pull requests merged in 2023-10, with the labels that each got.

#35 Fix. fingerprint login glitch
  lib/app/view/app.dart
Labels: hacktoberfest

#36 Added theme lush-green
  assets/images/lush-green.jpg
  lib/app/themes/lush_green_theme.dart
  lib/app/view/app.dart
  lib/features/auth/presentation/bloc/cubit/theme_state.dart
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: hacktoberfest

#37 Added share with friends option
  lib/core/pages/settings_page.dart
  lib/core/widgets/share_with_friends.dart
  pubspec.yaml
Labels: hacktoberfest

#41 Show send feedback button in the settings page.
  lib/core/pages/settings_page.dart
  lib/core/widgets/send_feedback.dart
  lib/core/widgets/share_with_friends.dart
  lib/core/widgets/version_number.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: hacktoberfest

#43 Impliment new generic setting tile.
  lib/core/widgets/send_feedback.dart
  lib/core/widgets/settings_tile.dart
  lib/core/widgets/share_with_friends.dart
  lib/core/widgets/version_number.dart
  lib/features/auth/presentation/widgets/security_settings.dart
  lib/features/auth/presentation/widgets/setup_account.dart
Labels: enhancement, hacktoberfest

#44 auto save notes #29
  lib/core/pages/settings_page.dart
  lib/core/widgets/auto_save_enable.dart
  lib/features/auth/core/constants.dart
  lib/features/auth/data/models/user_config_model.dart
  lib/features/notes/presentation/bloc/notes/notes_bloc.dart
  lib/features/notes/presentation/bloc/notes/notes_event.dart
  lib/features/notes/presentation/bloc/notes/notes_state.dart
  lib/features/notes/presentation/bloc/notes_fetch/notes_fetch_cubit.dart
  lib/features/notes/presentation/pages/note_create_page.dart
Labels: hacktoberfest

#49 Fixed readme
  README.md
Labels: hacktoberfest

#48 #39 - added accordion for security settings.
  lib/features/auth/presentation/widgets/security_settings.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest

#45 feat: Export as Delta/PDF/PlainText functionality.
  lib/features/notes/core/converters/delta_to_pdf.dart
  lib/features/notes/presentation/pages/note_read_only_page.dart
  lib/features/notes/presentation/widgets/note_export_button.dart
  lib/features/sync/data/datasources/dropbox_sync_client.dart
  lib/main.dart
  packages/flutter_quill/flutter_quill_extensions/lib/embeds/builders.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest

#66 Set up Github actions to detect syntax and formatting errors.
  .github/workflows/main.yml
  lib/app/themes/cosmic_theme.dart
  lib/core/databases/sqflite_setup.dart
  lib/features/auth/presentation/bloc/cubit/theme_state.dart
  pre-commit
Labels: help wanted, good first issue
